/** Bairros de Imperatriz-MA (lista oficial aproximada dos Correios). */
export const IMPERATRIZ_NEIGHBORHOODS = [
  "Aeroporto",
  "Alto Bonito do Triângulo",
  "Alto da Boa Vista",
  "Asa Norte",
  "Bacuri",
  "Beira Rio",
  "Boca da Mata",
  "Bom Jesus",
  "Bom Sucesso",
  "Brasil Novo",
  "Caema",
  "Centro",
  "Cidade Jardim",
  "Cinco Irmãos",
  "Coco Grande",
  "Conjunto Habitar Brasil",
  "Conjunto Nova Vitória",
  "Conjunto Planalto",
  "Conjunto Sebastião Régis",
  "Distrito Industrial",
  "Entroncamento",
  "Imigrantes",
  "Itamar Guará",
  "Jardim América",
  "Jardim Andrea",
  "Jardim Camboriú",
  "Jardim Cinco Estrelas",
  "Jardim Cristo Rei",
  "Jardim das Oliveiras",
  "Jardim Democrata",
  "Jardim Europa",
  "Jardim Lagoa",
  "Jardim Lopes",
  "Jardim Morada do Sol",
  "Jardim Oriental",
  "Jardim Pérola",
  "Jardim Planalto",
  "Jardim Primavera",
  "Jardim São Francisco",
  "Jardim São Luís",
  "Jardim Tropical",
  "João Paulo II",
  "Juçara",
  "Lagoinha",
  "Leandra",
  "Loteamento Santa Clara",
  "Maranhão Novo",
  "Mata Verde",
  "Mercadinho",
  "Morada do Bosque",
  "Mutirão",
  "Nova Imperatriz",
  "Novo Horizonte",
  "Ouro Verde",
  "Parque Alvorada",
  "Parque Alvorada II",
  "Parque Amazonas",
  "Parque Anhanguera",
  "Parque Avenida",
  "Parque Buriti",
  "Parque da Lagoa",
  "Parque das Estrelas",
  "Parque das Flores",
  "Parque das Mangueiras",
  "Parque das Mansões",
  "Parque das Palmeiras",
  "Parque das Palmeiras II",
  "Parque do Bosque",
  "Parque Independência",
  "Parque Planalto",
  "Parque Sanharol",
  "Parque Santa Lúcia",
  "Parque São José",
  "Parque Sumaré",
  "Parque Tocantins",
  "Parque Vitória",
  "Park Imperial",
  "Portal da Amazônia",
  "Recanto Estrela da Manhã",
  "Recanto Universitário",
  "Residencial Califórnia",
  "Residencial Colina Park",
  "Residencial Dom Afonso Felippe Gregory",
  "Residencial Eco Park",
  "Residencial Império Romano",
  "Residencial Kubitschek",
  "Residencial Sebastião Régis",
  "Residencial Teotônio Vilela",
  "Residencial Verona",
  "Santa Inês",
  "Santa Luzia",
  "Santa Rita",
  "Santo Amaro",
  "São José do Egito",
  "São Salvador",
  "Setor Parque de Exposições",
  "Setor Rodoviário",
  "Sol Nascente",
  "Super Quadra 602",
  "Três Poderes",
  "União",
  "Vale do Sol",
  "Vila Airton Senna",
  "Vila Bandeirantes",
  "Vila Brasil",
  "Vila Cafeteira",
  "Vila Carajás",
  "Vila Esmeralda",
  "Vila Fiquene",
  "Vila Independente",
  "Vila Ipiranga",
  "Vila Jardim",
  "Vila JK",
  "Vila João Castelo",
  "Vila Lobão",
  "Vila Macedo",
  "Vila Maderminas",
  "Vila Maria",
  "Vila Mariana",
  "Vila Nova",
  "Vila Palmares",
  "Vila Parati",
  "Vila Redenção",
  "Vila Redenção II",
  "Vila Verde",
  "Vila Vitória",
  "Vila Zenira",
  "Vilinha",
] as const;

export const OTHER_CITY_OPTION = "__outro_municipio__";

export function formatContactPlace(city: string, neighborhood: string) {
  if (city !== "Imperatriz") return city;
  return neighborhood && neighborhood !== "—" ? `${neighborhood} · Imperatriz` : "Imperatriz";
}
